### PR TITLE
fix: legacy send gas to 21000

### PR DESCRIPTION
**Pull request by yqrashawn**
Screenshot-2022-05-25-17 10 54@2x

### CODE REVIEW

**Comment by yqrashawn** [comment]
@seaona @jiexi 
sorry for the ping, any plan to merge this

**Review by jiexi — APPROVED** [review]
Thanks for catching this!

**Comment by yqrashawn** [comment]
Hey team! It looks like I don't have the permission to merge this. @jiexi, would you mind merging it for me? Thanks a bunch!

**Comment by dahu33** [comment]
Hi there, can we have this fix released? Thanks!

**Pull request merged**
