### PR TITLE
Fix event used for accessing provider

### PR DESCRIPTION
**Pull request by jpuri**
Using load event ensures that `window.ethereum` is always available in global scope when we access provider.

### CODE REVIEW

**Comment by Gudahtt** [comment]
The `load` event is not enough to guarantee that the provider is present on mobile. We have a library for blocking on the provider being injected (`@metamask/detect-provider`). Maybe that would be better here instead?

The reason the initialization was triggered by `DOMContentLoaded` is that the initialization _uses_ the DOM. It assumes all of the elements are on the page. Nothing happens on `load` that is directly tied to initialization.

**Comment by Gudahtt** [comment]
Oh I see, but we do use `window.ethereum` right away during initialization. Hmm.

OK this seems like an improvement that we could further improve later by using `@metamask/detect-provider`, for better mobile compatibility.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by adonesky1 — APPROVED** [review]
LGTM!

**Pull request merged**
